#!/bin/sh

# --------- Gradle Wrapper script ---------
# This file is auto-generated by 'gradle wrapper'.
# It downloads and runs the Gradle build tool.

# Set the location of the gradle-wrapper.jar
GRADLE_WRAPPER_DIR="$(dirname "$0")/gradle/wrapper"
GRADLE_WRAPPER_JAR="$GRADLE_WRAPPER_DIR/gradle-wrapper.jar"

# Download gradle-wrapper.jar if missing
if [ ! -f "$GRADLE_WRAPPER_JAR" ]; then
  echo "gradle-wrapper.jar not found. Please run 'gradle wrapper' on your local machine to generate it."
  exit 1
fi

# Run the wrapper jar
exec java -jar "$GRADLE_WRAPPER_JAR" "$@"
