@echo off
REM --------- Gradle Wrapper script ---------
REM This file is auto-generated by 'gradle wrapper'.
REM It downloads and runs the Gradle build tool.

set GRADLE_WRAPPER_JAR=%~dp0\gradle\wrapper\gradle-wrapper.jar

if not exist "%GRADLE_WRAPPER_JAR%" (
  echo gradle-wrapper.jar not found. Please run 'gradle wrapper' on your local machine to generate it.
  exit /b 1
)

java -jar "%GRADLE_WRAPPER_JAR%" %*
